name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison libgmp-dev

    - name: Download and install PBC library
      run: |
        cd /tmp
        wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
        tar -xzf pbc-0.5.14.tar.gz
        cd pbc-0.5.14
        ./configure
        make
        sudo make install
        sudo ldconfig

    - name: Install gtest
      run: |
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        make
        sudo make install
        sudo ldconfig

    - name: build(default BUILD_TESTS ON)
      run: |
        mkdir build
        cd build
        cmake ..
        make -j8

    - name: test
      run: |
        cd build
        ./bin/CP_ABE_test 
        ./bin/ABET_test  
        ./bin/RABE_XNM_test  
        ./bin/RABE_TMM_test  
        ./bin/ID_B_CollRes_XSL_2021_test  
        ./bin/MAPCH_ZLW_2021_test  
        ./bin/PCH_DSS_2019_test  
        ./bin/PCHBA_TLL_2020_test 
        ./bin/RPCH_TMM_2022_test 
        ./bin/RPCH_XNM_2021_test 
